### ISSUE TITLE
DBUnitでDataSetができない問題の解決（ImportRdbDataRunnerクラス）

### ISSUE THREAD

**Issue by krtkazuya** [epion-tropic-test-tool/epion-t3#24]
ImportRdbDataコマンドを用いてDBへのデータ投入を試みたところ、以下のようなエラーが発生しデータ投入ができませんでした。後述の解決策で一応データ投入はできているのでExcelやYamlに問題はありません。

コンソール出力エラー
```
2019-03-18 18:05:31,910 WARN  o.d.d.AbstractTableMetaData    - Potential problem found: The configured data type factory 'class org.dbunit.dataset.datatype.DefaultDataTypeFactory' might cause problems with the current database 'MySQL' (e.g. some datatypes may not be supported properly). In rare cases you might see this message because the list of supported database products is incomplete (list=[derby]). If so please request a java-class update via the forums.If you are using your own IDataTypeFactory extending DefaultDataTypeFactory, ensure that you override getValidDbProducts() to specify the supported database products. 
2019-03-18 18:05:31,911 WARN  o.d.d.DatabaseTableMetaData    - No columns found for table 'table_a' that are supported by dbunit. Will return an empty column list 
2019-03-18 18:05:31,914 ERROR f.r.i.CommandExecuteFlowRunner - ■ End Command   ■ Scenario ID : scenario-db-sample, Command ID : db-dataset-001, Execute Command ID : 7550ffde-0173-4493-a516-b768d4f55e04, Process Status : ERROR 
```
レポート出力エラー
```
Caused by: org.dbunit.dataset.NoSuchColumnException: table_a.column -  (Non-uppercase input column: character_id) in ColumnNameToIndexes cache map. Note that the map's column names are NOT case sensitive.
	at org.dbunit.dataset.AbstractTableMetaData.getColumnIndex(AbstractTableMetaData.java:117)
	at org.dbunit.operation.AbstractOperation.getOperationMetaData(AbstractOperation.java:89)
	at org.dbunit.operation.AbstractBatchOperation.execute(AbstractBatchOperation.java:151)
	at com.zomu.t.epion.tropic.test.tool.rdb.command.runner.ImportRdbDataRunner.execute(ImportRdbDataRunner.java:154)
	... 23 more
```

https://stackoverflow.com/questions/4877034/dbunit-nosuchcolumnexception-and-case-sensitivity
上記のサイトを参考にし、com.zomu.t.epion.tropic.test.tool.rdb.command.runner.ImportRdbDataRunnerクラス (154行目付近)
を以下のように修正したところMySQLへのデータ投入が可能になりました。  

```
                    // オペレーション実行
                    conn.getConfig().setProperty(DatabaseConfig.PROPERTY_DATATYPE_FACTORY, new MySqlDataTypeFactory());
                    conn.getConfig().setProperty(DatabaseConfig.PROPERTY_METADATA_HANDLER, new MySqlMetadataHandler());
                    operationType.getOperation().execute(conn, iDataSet);
```
IDatabaseConnectionの派生クラスであるMySqlConnectionにも同様の記述がされているので、必要なのではと思いissueを作成しました。

【おまけ】
RDBガイドの「ImportRdbDataRunner」のコマンド名が「ImportRdbDataRunner」となっていますが、コマンドIDは「ImportRdbData」なので修正しておいた方がいいと思います。
https://ettt.t-zomu.com/#/pages/specification/command/rdb

**Comment by krtkazuya** [comment]
自分の環境では、
```
configMysql.setProperty(DatabaseConfig.PROPERTY_METADATA_HANDLER, new MySqlMetadataHandler());
```
も入れないと、カラム名がうまく取得できずDataSetできない状態です。

**Comment by takashno** [comment]
対応済。
確認済。
