### ISSUE TITLE
ExecuteRestApiコマンドのHTML出力時にエラーが発生する

### ISSUE THREAD

**Issue by krtkazuya** [epion-tropic-test-tool/epion-t3#25]
1次解析を試みたが、時間がかかりそうなので断念。
コマンド自体は成功するので、アプリ自体が落ちるわけではない。

自分のタスクに影響度は低いと思うので、優先していただかなくて大丈夫です。
とりあえずスタックトレースだけ載せておきます
```
2019-03-19 19:17:00,818 INFO  ProcessLog                     - StatusCode:200 
2019-03-19 19:17:00,818 INFO  ProcessLog                     - Headers: 
2019-03-19 19:17:00,818 INFO  ProcessLog                     - content-type:[application/json;charset=UTF-8] 
2019-03-19 19:17:00,818 INFO  ProcessLog                     - date:[Tue, 19 Mar 2019 10:17:00 GMT] 
2019-03-19 19:17:00,818 INFO  ProcessLog                     - transfer-encoding:[chunked] 
2019-03-19 19:17:00,818 INFO  ProcessLog                     - Body:{"result":{"message":null,"code":"success"}} 
2019-03-19 19:17:00,827 ERROR org.thymeleaf.TemplateEngine   - [THYMELEAF][main] Exception processing template "execute-rest-api-report": Exception evaluating OGNL expression: "stringUtils.prettyHtml(jsonUtils.rePretty(request.body))" (template: "execute-rest-api-report" - line 52, col 31) 
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "stringUtils.prettyHtml(jsonUtils.rePretty(request.body))" (template: "execute-rest-api-report" - line 52, col 31)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:191)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:95)
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:165)
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138)
	at org.thymeleaf.standard.processor.StandardUtextTagProcessor.doProcess(StandardUtextTagProcessor.java:87)
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314)
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136)
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1059)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1048)
	at com.zomu.t.epion.tropic.test.tool.core.command.reporter.impl.AbstractThymeleafCommandReporter.report(AbstractThymeleafCommandReporter.java:95)
	at com.zomu.t.epion.tropic.test.tool.core.command.runner.impl.AbstractCommandRunner.execute(AbstractCommandRunner.java:139)
	at com.zomu.t.epion.tropic.test.tool.core.command.runner.impl.AbstractCommandRunner.execute(AbstractCommandRunner.java:1)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.zomu.t.epion.tropic.test.tool.core.command.handler.CommandRunnerInvocationHandler.invoke(CommandRunnerInvocationHandler.java:88)
	at com.sun.proxy.$Proxy19.execute(Unknown Source)
	at com.zomu.t.epion.tropic.test.tool.core.flow.runner.impl.CommandExecuteFlowRunner.execute(CommandExecuteFlowRunner.java:119)
	at com.zomu.t.epion.tropic.test.tool.core.flow.runner.impl.CommandExecuteFlowRunner.execute(CommandExecuteFlowRunner.java:1)
	at com.zomu.t.epion.tropic.test.tool.core.flow.runner.impl.AbstractFlowRunner.execute(AbstractFlowRunner.java:98)
	at com.zomu.t.epion.tropic.test.tool.core.flow.runner.impl.AbstractFlowRunner.execute(AbstractFlowRunner.java:1)
	at com.zomu.t.epion.tropic.test.tool.core.scenario.runner.impl.ScenarioRunnerImpl.executeScenario(ScenarioRunnerImpl.java:188)
	at com.zomu.t.epion.tropic.test.tool.core.scenario.runner.impl.ScenarioRunnerImpl.execute(ScenarioRunnerImpl.java:68)
	at com.zomu.t.epion.tropic.test.tool.core.scenario.runner.impl.ScenarioRunnerImpl.execute(ScenarioRunnerImpl.java:1)
	at com.zomu.t.epion.tropic.test.tool.core.application.runner.impl.ApplicationRunnerImpl.execute(ApplicationRunnerImpl.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.zomu.t.epion.tropic.test.tool.application.Application.main(Application.java:100)
	at com.zomu.t.epion.tropic.test.tool.application.ApplicationTest.main(ApplicationTest.java:18)
Caused by: ognl.MethodFailedException: Method "rePretty" failed for object com.zomu.t.epion.tropic.test.tool.core.util.JsonUtils@15d42ccb
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1551)
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1615)
	at ognl.ASTMethod.getValueBody(ASTMethod.java:91)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTMethod.getValueBody(ASTMethod.java:88)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.Ognl.getValue(Ognl.java:467)
	at ognl.Ognl.getValue(Ognl.java:431)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.executeExpression(OGNLVariableExpressionEvaluator.java:316)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:170)
	... 39 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:889)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at com.zomu.t.epion.tropic.test.tool.core.util.JsonUtils.rePretty(JsonUtils.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:894)
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1539)
	... 57 common frames omitted
2019-03-19 19:17:00,828 ERROR stractThymeleafCommandReporter - ee 
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "stringUtils.prettyHtml(jsonUtils.rePretty(request.body))" (template: "execute-rest-api-report" - line 52, col 31)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:191)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:95)
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:165)
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138)
	at org.thymeleaf.standard.processor.StandardUtextTagProcessor.doProcess(StandardUtextTagProcessor.java:87)
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314)
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136)
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1059)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1048)
	at com.zomu.t.epion.tropic.test.tool.core.command.reporter.impl.AbstractThymeleafCommandReporter.report(AbstractThymeleafCommandReporter.java:95)
	at com.zomu.t.epion.tropic.test.tool.core.command.runner.impl.AbstractCommandRunner.execute(AbstractCommandRunner.java:139)
	at com.zomu.t.epion.tropic.test.tool.core.command.runner.impl.AbstractCommandRunner.execute(AbstractCommandRunner.java:1)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.zomu.t.epion.tropic.test.tool.core.command.handler.CommandRunnerInvocationHandler.invoke(CommandRunnerInvocationHandler.java:88)
	at com.sun.proxy.$Proxy19.execute(Unknown Source)
	at com.zomu.t.epion.tropic.test.tool.core.flow.runner.impl.CommandExecuteFlowRunner.execute(CommandExecuteFlowRunner.java:119)
	at com.zomu.t.epion.tropic.test.tool.core.flow.runner.impl.CommandExecuteFlowRunner.execute(CommandExecuteFlowRunner.java:1)
	at com.zomu.t.epion.tropic.test.tool.core.flow.runner.impl.AbstractFlowRunner.execute(AbstractFlowRunner.java:98)
	at com.zomu.t.epion.tropic.test.tool.core.flow.runner.impl.AbstractFlowRunner.execute(AbstractFlowRunner.java:1)
	at com.zomu.t.epion.tropic.test.tool.core.scenario.runner.impl.ScenarioRunnerImpl.executeScenario(ScenarioRunnerImpl.java:188)
	at com.zomu.t.epion.tropic.test.tool.core.scenario.runner.impl.ScenarioRunnerImpl.execute(ScenarioRunnerImpl.java:68)
	at com.zomu.t.epion.tropic.test.tool.core.scenario.runner.impl.ScenarioRunnerImpl.execute(ScenarioRunnerImpl.java:1)
	at com.zomu.t.epion.tropic.test.tool.core.application.runner.impl.ApplicationRunnerImpl.execute(ApplicationRunnerImpl.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.zomu.t.epion.tropic.test.tool.application.Application.main(Application.java:100)
	at com.zomu.t.epion.tropic.test.tool.application.ApplicationTest.main(ApplicationTest.java:18)
Caused by: ognl.MethodFailedException: Method "rePretty" failed for object com.zomu.t.epion.tropic.test.tool.core.util.JsonUtils@15d42ccb
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1551)
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1615)
	at ognl.ASTMethod.getValueBody(ASTMethod.java:91)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTMethod.getValueBody(ASTMethod.java:88)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.Ognl.getValue(Ognl.java:467)
	at ognl.Ognl.getValue(Ognl.java:431)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.executeExpression(OGNLVariableExpressionEvaluator.java:316)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:170)
	... 39 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:889)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at com.zomu.t.epion.tropic.test.tool.core.util.JsonUtils.rePretty(JsonUtils.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:894)
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1539)
	... 57 common frames omitted
2019-03-19 19:17:00,828 INFO  f.r.i.CommandExecuteFlowRunner - ■ End Command   ■ Scenario ID : scenario-IF_R0005, Command ID : rest-002, Execute Command ID : 7409f136-3528-4c80-a716-44a33cf3580c, Process Status : SUCCESS 
```

**Comment by takashno** [comment]
対応済。
